image: node:18

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build-pages:
  tags: [cpu]
  image: ubuntu:latest
  stage: build
  script:
    - echo 'APT::Sandbox::User "root";' > /etc/apt/apt.conf.d/sandbox-disable
    - apt-get update
    - apt-get install -qq -y nodejs npm 
    - npm install
    - npm run build
    - mv out public  # For Next.js static export
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - echo "Deployed to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main
