image: node:18
stages:
  - build
  - deploy

build-pages:
  tags: [cpu]
  stage: build
  before_script:
    # Clean npm cache and temporary files
    - npm cache clean --force
    - rm -rf node_modules/ package-lock.json .npm/
  script:
    - echo "Installing dependencies..."
    # Force clean installation with legacy peer deps
    - NODE_ENV=production npm install --legacy-peer-deps --force --no-audit --prefer-offline
    
    - echo "Building project..."
    - npm run build

    - if [ -d out ]; then mv out public; else echo "❌ Build output folder 'out' not found!"; exit 1; fi
  artifacts:
    paths:
      - public
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - echo "Deployed to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main