image: node:18
stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

build-pages:
  tags: [cpu]
  stage: build
  before_script:
    - npm cache clean --force
    - npm install -g npm@latest
  script:
    - echo "Installing dependencies..."
    - npm install --legacy-peer-deps --no-audit --prefer-offline

    # Install required peer dependencies
    - npm install tailwindcss postcss autoprefixer --save-exact

    - echo "Building project..."
    - npm run build

    # Next.js typically outputs to .next/static - adjust as needed
    - mkdir -p public
    - cp -r .next/static public/_next/static || echo "No static files found"
    - cp -r public/* ./public/ || echo "No public assets found"
  artifacts:
    paths:
      - public
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages..."
  artifacts:
    paths:
      - public
  only:
    - main