image: node:18

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build-pages:
  tags: [cpu]
  stage: build
  script:
    - echo "Installing dependencies..."

    # Check if package-lock.json exists
    - if [ -f package-lock.json ]; then
        NODE_ENV=production npm ci;
      else
        echo "⚠️ package-lock.json not found. Falling back to npm install";
        NODE_ENV=production npm install;
      fi

    - echo "Building project..."
    - npm run build

    # Ensure build folder exists before moving
    - if [ -d out ]; then mv out public; else echo "❌ Build output folder 'out' not found!"; exit 1; fi
  artifacts:
    paths:
      - public
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - echo "Deployed to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main
