image: node:18
stages:
  - build
  - deploy

cache:
  key:
    files:
      - pnpm-lock.yaml
    prefix: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .pnpm-store/
    - .next/cache/

variables:
  PNPM_VERSION: "8.15.6"

before_script:
  - npm install -g pnpm@${PNPM_VERSION}
  - pnpm config set store-dir .pnpm-store

build-pages:
  tags: [cpu]
  stage: build
  script:
    - echo "Installing dependencies..."
    # Check for lockfile existence
    - if [ -f pnpm-lock.yaml ]; then
        pnpm install --frozen-lockfile;
      else
        echo "⚠️ pnpm-lock.yaml not found. Generating fresh install";
        pnpm install;
      fi

    - echo "Building project..."
    - pnpm build

    # Handle Next.js output based on config
    - if [ -d out ]; then mv out public;
      elif [ -d .next/static ]; then mkdir -p public/_next && cp -r .next/static public/_next/static;
      else echo "❌ No build output found"; exit 1;
      fi
  artifacts:
    paths:
      - public
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - echo "Deployed to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main