image: node:18

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build-pages:
  tags: [cpu]
  stage: build
  script:
    - echo "Installing dependencies..."
    - NODE_ENV=production npm ci
    - echo "Building project..."
    - npm run build
    - mv out public  # For Next.js static export (make sure you're using `next export`)
  artifacts:
    paths:
      - public
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - echo "Deployed to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main
