image: node:18
stages:
  - build
  - deploy

cache:
  key:
    files:
      - pnpm-lock.yaml
    prefix: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .pnpm-store/
    - .next/cache/

variables:
  PNPM_VERSION: "8.15.6"

before_script:
  # Install compatible pnpm version first
  - npm install -g pnpm@${PNPM_VERSION}
  - pnpm config set store-dir .pnpm-store

build-pages:
  tags: [cpu]
  stage: build
  script:
    - echo "Installing dependencies..."
    - pnpm install --frozen-lockfile

    - echo "Building project..."
    - pnpm build

    # For Next.js static export
    - pnpm export -o public

  artifacts:
    paths:
      - public
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - echo "Deployed to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main