image: node:18
stages:
  - build
  - deploy

cache:
  key:
    files:
      - package-lock.json
    prefix: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

build-pages:
  tags: [cpu]
  stage: build
  before_script:
    - npm config set cache .npm --global
    - npm install -g npm@latest
  script:
    - echo "Clearing any existing node_modules..."
    - rm -rf node_modules/
    
    - echo "Installing dependencies..."
    # Prefer package-lock.json, but use npm install with legacy peer-deps if missing
    - if [ -f package-lock.json ]; then
        NODE_ENV=production npm ci --legacy-peer-deps;
      else
        echo "⚠️ package-lock.json not found. Using npm install";
        NODE_ENV=production npm install --legacy-peer-deps;
      fi

    - echo "Building project..."
    - npm run build

    - if [ -d out ]; then mv out public; else echo "❌ Build output folder 'out' not found!"; exit 1; fi
  artifacts:
    paths:
      - public
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - echo "Deployed to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - main